# Generated by Django 5.2.3 on 2025-06-14 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Empresa')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ParametrosEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_abertura', models.TimeField(verbose_name='Horário de Abertura')),
                ('horario_fechamento', models.TimeField(verbose_name='Horário de Fechamento')),
                ('intervalo_agendamento', models.PositiveIntegerField(default=30, help_text='Duração mínima dos slots de agendamento em minutos', verbose_name='Intervalo de Agendamento (minutos)')),
                ('dias_funcionamento', models.CharField(help_text='Dias da semana separados por vírgula (ex: seg,ter,qua,qui,sex)', max_length=50, verbose_name='Dias de Funcionamento')),
                ('antecedencia_minima', models.PositiveIntegerField(default=60, help_text='Tempo mínimo de antecedência para agendamentos', verbose_name='Antecedência Mínima (minutos)')),
                ('antecedencia_cancelamento', models.PositiveIntegerField(default=120, help_text='Tempo mínimo de antecedência para cancelar agendamentos', verbose_name='Antecedência para Cancelamento (minutos)')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Parâmetros da Empresa',
                'verbose_name_plural': 'Parâmetros das Empresas',
            },
        ),
    ]
