# Generated by Django 5.2.3 on 2025-06-14 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('cargo', models.CharField(help_text='Ex: Barbeiro, Manicure, Esteticista', max_length=100, verbose_name='Cargo')),
                ('especialidade', models.CharField(blank=True, help_text='Especialidades específicas do funcionário', max_length=200, verbose_name='Especialidade')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_contratacao', models.DateField(verbose_name='Data de Contratação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome'],
                'unique_together': {('empresa', 'email')},
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadeFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('horario_inicio', models.TimeField(verbose_name='Horário de Início')),
                ('horario_fim', models.TimeField(verbose_name='Horário de Fim')),
                ('tipo', models.CharField(choices=[('trabalho', 'Período de Trabalho'), ('folga', 'Folga'), ('almoco', 'Almoço'), ('pausa', 'Pausa'), ('outro', 'Outro')], default='trabalho', max_length=20, verbose_name='Tipo')),
                ('observacao', models.TextField(blank=True, help_text='Detalhes adicionais sobre este período', verbose_name='Observação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='funcionarios.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Disponibilidade do Funcionário',
                'verbose_name_plural': 'Disponibilidades dos Funcionários',
                'ordering': ['data', 'horario_inicio'],
                'unique_together': {('funcionario', 'data', 'horario_inicio', 'horario_fim')},
            },
        ),
    ]
