# Generated by Django 5.2.3 on 2025-06-14 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionarioServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_especifico', models.DecimalField(blank=True, decimal_places=2, help_text='Preço específico deste funcionário para este serviço (opcional)', max_digits=10, null=True, verbose_name='Preço Específico')),
                ('duracao_especifica', models.PositiveIntegerField(blank=True, help_text='Duração específica deste funcionário para este serviço (opcional)', null=True, verbose_name='Duração Específica (minutos)')),
                ('data_associacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Associação')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Funcionário-Serviço',
                'verbose_name_plural': 'Funcionários-Serviços',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Serviço')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do serviço', verbose_name='Descrição')),
                ('duracao', models.PositiveIntegerField(help_text='Duração média do serviço em minutos', verbose_name='Duração (minutos)')),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço base do serviço', max_digits=10, verbose_name='Preço')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='core.empresa', verbose_name='Empresa')),
                ('funcionarios', models.ManyToManyField(related_name='servicos', through='servicos.FuncionarioServico', to='funcionarios.funcionario', verbose_name='Funcionários')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['nome'],
                'unique_together': {('empresa', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='funcionarioservico',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.servico', verbose_name='Serviço'),
        ),
        migrations.AlterUniqueTogether(
            name='funcionarioservico',
            unique_together={('funcionario', 'servico')},
        ),
    ]
